apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: gitops-webapp
  template:
    metadata:
      labels:
        app: gitops-webapp
    spec:
      containers:
      - name: webapp
        # 注意這裡！CI 機器人等一下會自動來把 TAG_PLACEHOLDER 替換成最新的版本號
        image: mudd886asme7/gitops-webapp:49fb0af560ed9610e572ad6ef301033a5e1a4ff7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-webapp-svc
spec:
  selector:
    app: gitops-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
