apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitops-webapp
  template:
    metadata:
      labels:
        app: gitops-webapp
    spec:
      containers:
      - name: webapp
        # 注意這裡！CI 機器人等一下會自動來把 TAG_PLACEHOLDER 替換成最新的版本號
        image: mudd886asme7/gitops-webapp:7ec71d71106abe1853da1bd1e00017f885f6c0ff
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-webapp-svc
spec:
  selector:
    app: gitops-webapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
