apiVersion: v1
kind: Service
metadata:
  name: my-gitops-webapp-service
  namespace: terraform-practice
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80